namespace DevOps.Primitives.CSharp.Helpers.Common
{
    public static class Classes
    {
        public static ClassDeclaration Internal(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.Internal,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);

        public static ClassDeclaration InternalStatic(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.InternalStatic,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);

        public static ClassDeclaration Private(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.Private,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);

        public static ClassDeclaration PrivateStatic(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.PrivateStatic,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);

        public static ClassDeclaration Public(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.Public,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);

        public static ClassDeclaration PublicStatic(
            in string identifier,
            in string @namespace,
            in UsingDirectiveList usingDirectiveList = default,
            in DocumentationCommentList documentationCommentList = default,
            in AttributeListCollection attributeListCollection = default,
            in TypeParameterList typeParameterList = default,
            in ConstraintClauseList constraintClauseList = default,
            in BaseList baseList = default,
            in ConstructorList constructorList = default,
            in FieldList fieldList = default,
            in MethodList methodList = default,
            in PropertyList propertyList = default,
            in Finalizer finalizer = default)
            => new ClassDeclaration(
                in identifier,
                in @namespace,
                in ModifierLists.PublicStatic,
                in usingDirectiveList,
                in documentationCommentList,
                in attributeListCollection,
                in typeParameterList,
                in constraintClauseList,
                in baseList,
                in constructorList,
                in fieldList,
                in methodList,
                in propertyList,
                in finalizer);
    }
}
